repos:  # Run `pre-commit run` before `git commit`
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
exclude: 'airflow/.*'
